### ISSUE TITLE
highlight bug

### ISSUE THREAD

**Issue by Parth** [lockbook/lockbook#2023] opened 2023-09-01 00:38 UTC
the text:

```
Additionally, prior to purchasing this car I spent some time watching videos like [this](https://www.youtube.com/watch?v=bbagu1H_x-M) one which chronicle common miata problems. 
```

causes the problem:

https://github.com/lockbook/lockbook/assets/821972/e30a256d-4ea5-419f-a412-f121e519861e

**Comment by tvanderstad** [comment] 2023-09-04 16:49
duplicate of #2016

**Closed by tvanderstad** 2023-09-04 16:49 UTC
Labels: editor
