### ISSUE TITLE
Server timestamp generation is not atomic 

### ISSUE THREAD

**Issue by Parth** [lockbook/lockbook#73] opened 2020-05-18 00:12 UTC

**Comment by tvanderstad** [comment] 2020-05-31 22:09
Use case: client 1 generates version, client 2 generates version, client 2 updates metadata, client 3 gets, client 1 updates metadata, client 3 has more recent version than active metadata and never receives active metadata

**Comment by tvanderstad** [comment] 2020-05-31 22:41
Duplicate of #98

**Closed by tvanderstad** 2020-05-31 22:41 UTC
