### ISSUE TITLE
typing backtick double hyphen transforms to double backtick hyphen in iOS editor

### ISSUE THREAD

**Issue by smailbarkouch** [lockbook/lockbook#2050] opened 2023-09-06 14:18 UTC
`-- becomes ``-

**Comment by tvanderstad** [comment] 2023-09-17 16:22
actually, it becomes ``—

**Comment by tvanderstad** [comment] 2023-09-17 16:23
typing `--` on a new line crashes the editor

**Comment by tvanderstad** [comment] 2023-09-17 16:29
I'm not able to reproduce either of these issues in the simulator on master; can you try deploying master to your phone?

**Comment by tvanderstad** [comment] 2023-09-17 16:41
confirmed broken in [0.8](https://github.com/lockbook/lockbook/commit/80cdbd96adacde83b7de6f41a811c63a7bf1aeaa) and fixed on [master](https://github.com/lockbook/lockbook/commit/ef387b2b842ccb9112cf7f8992c9f4db922f5e9b)

**Closed by tvanderstad** 2023-09-17 16:41 UTC
Labels: apple, editor

**Comment by tvanderstad** [comment] 2023-09-17 16:45
related: https://github.com/lockbook/lockbook/issues/2090
