### ISSUE TITLE
new file workspace button broken on iPad

### ISSUE THREAD

**Issue by smailbarkouch** [lockbook/lockbook#2816] opened 2024-08-27 21:33 UTC

**Comment by Parth** [comment] 2024-08-29 18:35
Requested by @mehrotra-rahul

**Comment by tvanderstad** [comment] 2024-09-27 14:18
Failed to reproduce on master and 0.9.7 which was the release close to when this issue was opened (macOS, egui on macOS)

**Comment by tvanderstad** [comment] 2024-09-27 14:36
also duplicate of https://github.com/lockbook/lockbook/issues/2690

**Comment by Parth** [comment] 2024-09-27 15:02
I took out my ipad and was able to repro. I pressed it twice, you can see the files are created but some state change message is lost because these never opened:

![IMG_0029](https://github.com/user-attachments/assets/9c5c4f51-4167-4cef-9b3f-dba0824cd8ec)
![IMG_0030](https://github.com/user-attachments/assets/298f43b4-8838-4b9c-99dc-9ff4b2bd356e)

**Comment by Parth** [comment] 2024-09-27 15:52
I just got sent this: 
<img width="524" alt="image" src="https://github.com/user-attachments/assets/524a0c56-acda-4f29-960d-880ae292a041">

**Closed** 2024-09-27 17:23 UTC
Labels: apple
