### ISSUE TITLE
bulleted lists with checkboxes mixed in don't show up as checkboxes 

### ISSUE THREAD

**Issue by Parth** [lockbook/lockbook#1606] opened 2023-02-23 22:36 UTC
![image](https://user-images.githubusercontent.com/821972/221046237-8fff1aa9-a5fe-4613-9132-ffb671f47d83.png)

**Comment by tvanderstad** [comment] 2023-03-18 15:59
minimally reproducing doc:
```
- [ ] 

-
```

**Comment by tvanderstad** [comment] 2023-03-18 16:33
the AST produced in this case places `[ ]` in a paragraph rather than the item; this is due to a [pulldown-cmark bug](https://github.com/raphlinus/pulldown-cmark/issues/557) which is fixed by a [PR](https://github.com/raphlinus/pulldown-cmark/pull/558) which has been open since Jan 2022

**Comment by tvanderstad** [comment] 2024-02-18 16:22
fixed upstream

**Closed by tvanderstad** 2024-02-18 16:22 UTC
Labels: external, editor
