### ISSUE TITLE
canvas crashes when erasing

### ISSUE THREAD

**Issue by tvanderstad** [lockbook/lockbook#2373] opened 2024-02-03 18:23 UTC
Observed on egui, windows, and macos apps on branches master and pane. I just open the attached svg and erase anywhere. Github renders it invisibly but just click below this text to download the attachment.
![2024-02-03-components](https://github.com/lockbook/lockbook/assets/6198756/15b5f182-0e1a-483b-9a9f-e888ba01ae24)

**Comment by ad-tra** [comment] 2024-02-08 21:12
dupe of https://github.com/lockbook/lockbook/issues/2298

**Closed by ad-tra** 2024-02-08 21:12 UTC
Labels: canvas
