### ISSUE TITLE
editor image import refinements 

### ISSUE THREAD

**Issue by Parth** [lockbook/lockbook#2665] opened 2024-05-12 18:39 UTC
selected location - home breaks sharing.

further consideration to where images end up, ideally in a location that doesn't clutter file tree all that much.

it's okay for now to break document sharing in favor of fixing the behavior for folder sharing.

target state for document sharing would be to identify which sharee's won't be able to see image contents.

**Comment by tvanderstad** [comment] 2024-06-19 19:22
duplicate of https://github.com/lockbook/lockbook/issues/2570

**Closed by tvanderstad** 2024-06-19 19:22 UTC
Labels: editor
