### ISSUE TITLE
numbered list reordering greatness

### ISSUE THREAD

**Issue by Parth** [lockbook/lockbook#1741] opened 2023-04-22 16:10 UTC

**Comment by tvanderstad** [comment] 2023-06-19 16:32
Not sure how to reproduce, but I regularly end up with a mess when modifying a numbered list. Need to rework this with a new UX, possibly renumber the whole list from the beginning when there's a relevant change

**Comment by tvanderstad** [comment] 2023-09-17 22:03
My messes usually came from some weirdness around newlines which was resolved a while ago. The only actionable improvement I'm interested in taking on this for now is for deleting list elements to trigger renumbering.

**Comment by tvanderstad** [comment] 2024-02-17 18:05
duplicate of https://github.com/lockbook/lockbook/issues/2326

**Closed by tvanderstad** 2024-02-17 18:05 UTC
Labels: editor
