### ISSUE TITLE
iPadOS rendering issues while multitasking

### ISSUE THREAD

**Issue by tvanderstad** [lockbook/lockbook#2871] opened 2024-09-26 14:19 UTC
Things that sometimes happen when switching to the app:
* workspace not rendered at all
* tab strip not rendered or flickers

https://discord.com/channels/1014184997751619664/1288694029889830973/1288701227802165248

**Comment by smailbarkouch** [comment] 2024-09-26 16:01
dupe of https://github.com/lockbook/lockbook/issues/2765

**Closed** 2024-09-26 16:10 UTC
Labels: apple
